# Generated by Django 4.1 on 2023-04-20 18:20

from django.db import migrations

GROUPS = [
    {
        'name': 'ci_user',
    },
    {
        'name': 'ci_scheduler',
    },
    {
        'name': 'ci_registrar',
    },
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_alter_course_options_course_unique_course'),
    ]

    operations = [

        migrations.RunPython(
            add_group_data,
            remove_group_data
        )

    ]